# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/elina/CapstoneVHDL/ECG_Compression/ECG_Compression.srcs/sources_1/ip/bram_ecg/bram_ecg.xci
# IP: The module: 'bram_ecg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elina/CapstoneVHDL/ECG_Compression/ECG_Compression.gen/sources_1/ip/bram_ecg/bram_ecg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_ecg'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/elina/CapstoneVHDL/ECG_Compression/ECG_Compression.srcs/sources_1/ip/bram_ecg/bram_ecg.xci
# IP: The module: 'bram_ecg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elina/CapstoneVHDL/ECG_Compression/ECG_Compression.gen/sources_1/ip/bram_ecg/bram_ecg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_ecg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
